### ISSUE TITLE
Initial graph view bug

### ISSUE THREAD

**Issue by varunbhoopalam** [varunbhoopalam/slipbox#31]
The initial graph view should be your entire slipbox. Currently it may be zoomed in for some users depending on how many notes they have.

**Comment by vbruick** [comment]
I think this issue is related, so I'm adding it here. I clicked on a dot in my graph view that as towards the bottom of the screen. I expected the graph view to shift to center that note, but instead it opened the note preview out of frame, so I couldn't read it. I expected to be able to scroll to shift my view, but scrolling did nothing. I click and dragged the screen, and was able to adjust the view, but the dragging was almost too responsive and the notes all shot out of view.
